#!/bin/bash

time=0
while true; do
  newtime=$(find ./*.rb -exec stat -f "%m" \{} \; | sort -n -r | head -1)
  if [ "$newtime" -gt "$time" ]; then
      clear
      rspec lisp_spec.rb --color
  fi

  time=$newtime;
  sleep 1
done
